#!/bin/bash

# --- CONFIGURATION ---
REPO_DIR="$HOME/AIModel"  # Change this if repo is located elsewhere
REPO_URL="https://github.com/AIwork2024/AIModel.git"
BRANCH="feature/AIUpdates"
TARGET_BRANCH="main"
COMMIT_MSG="?? Auto-updated XPath using Gemini AI"
PR_TITLE="? Gemini AI Auto XPath Update"
PR_BODY="This PR contains updated XPath selectors automatically generated by Gemini AI."

# --- CLONE OR NAVIGATE TO REPO ---
if [ ! -d "$REPO_DIR/.git" ]; then
    echo "?? Cloning repository..."
    git clone "$REPO_URL" "$REPO_DIR"
else
    echo "?? Repository already cloned."
fi

cd "$REPO_DIR" || { echo "? Failed to access $REPO_DIR"; exit 1; }

# --- SET GIT REMOTE (optional safety) ---
git remote set-url origin "$REPO_URL"

# --- CREATE/SWITCH TO FEATURE BRANCH ---
git fetch origin
git checkout "$BRANCH" 2>/dev/null || git checkout -b "$BRANCH" origin/"$TARGET_BRANCH"
git pull origin "$BRANCH"

# --- ADD AND COMMIT CHANGES ---
git add .
if git diff --cached --quiet; then
    echo "?? No changes to commit."
else
    echo "? Committing changes..."
    git commit -m "$COMMIT_MSG"
    git push origin "$BRANCH"
fi

# --- CREATE A PULL REQUEST ---
echo "?? Creating pull request..."
gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base "$TARGET_BRANCH" --head "$BRANCH"
